import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { WhatsAppButton } from "@/components/Whatsapp";
import SmoothScroll from "@/components/SmoothScroll";

// Import Inter from Google Fonts
import { Inter } from "next/font/google";
import localFont from "next/font/local";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// For Poppins, either import from Google Fonts
import { Poppins } from "next/font/google";
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

// export const metadata = {
//   title: "SDEC",
//   description: "Generated by SDEC",
// };

export const metadata = {
  title: "SDEC",
  description:
    "Generated by SDEC - Comprehensive description that includes relevant keywords",
  keywords: ["relevant", "keywords", "for", "your", "website"],
  openGraph: {
    title: "SDEC",
    description:
      "Generated by SDEC - Comprehensive description for social sharing",
    url: "https://sdec.me",
    siteName: "SDEC",
    images: [
      {
        url: "https://sdec.me/og-image.jpg",
        width: 1200,
        height: 630,
      },
    ],
    locale: "en_US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
  },
  twitter: {
    card: "summary_large_image",
    title: "SDEC",
    description: "Generated by SDEC - Comprehensive description for Twitter",
    images: ["https://sdec.me/twitter-image.jpg"],
  },
  alternates: {
    canonical: "https://sdec.me",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
         <body
        className={`${poppins.variable} ${inter.variable} font-poppins antialiased`}
      >
         <SmoothScroll>
        <Navbar />
        {children}
        <WhatsAppButton />
        <Footer />
        </SmoothScroll>
      </body>
     
     
    </html>
  );
}
