import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import { WhatsAppButton } from "@/components/Whatsapp";

// Import Inter from Google Fonts
import { Inter } from "next/font/google";
import localFont from "next/font/local";
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// For Poppins, either import from Google Fonts
import { Poppins } from "next/font/google";
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "SDEC",
  description: "Generated by SDEC",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} font-poppins antialiased`}
      >
        {/* <Navbar /> */}
        {children}
        {/* <WhatsAppButton />
        <Footer /> */}
      </body>
    </html>
  );
}
