
import "./globals.css";
import Navbar from "@/components/Navbar";

import { Inter } from "next/font/google";
import localFont from "next/font/local";

// Import Inter from Google Fonts
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// For Poppins, either import from Google Fonts
import { Poppins } from "next/font/google";
const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body
  className={`${poppins.variable} ${inter.variable} font-poppins antialiased`}
>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
